config/routes.rb
Smser::Application.routes.draw do

  resources :messages

  devise_for :users

  root to: "users#index"

  

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
	before_filter :authenticate_user!
	
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :find_message, :only => [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all

    respond_to do |wants|
      wants.html # index.html.erb
      wants.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    respond_to do |wants|
      wants.html # show.html.erb
      wants.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |wants|
      wants.html # new.html.erb
      wants.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |wants|
      if @message.save
        flash[:notice] = 'Message was successfully created.'
        wants.html { redirect_to(@message) }
        wants.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        wants.html { render :action => "new" }
        wants.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    respond_to do |wants|
      if @message.update_attributes(params[:message])
        flash[:notice] = 'Message was successfully updated.'
        wants.html { redirect_to(@message) }
        wants.xml  { head :ok }
      else
        wants.html { render :action => "edit" }
        wants.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message.destroy

    respond_to do |wants|
      wants.html { redirect_to(messages_url) }
      wants.xml  { head :ok }
    end
  end

  private
    def find_message
      @message = Message.find(params[:id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : name %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Smser", root_path, :class => 'brand' %>
<ul class="nav">
  
  <% if user_signed_in? %>
   <li><%= link_to 'Edit account', edit_user_registration_path %></li>
	<li><%= link_to 'Messages', new_message_path %></li>
    <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
    <li><%= link_to 'Login', new_user_session_path %></li>
	<li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Smser" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Smser" %>">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<h1>Messages#_form</h1>
<p>Find me in app/views/messages/_form.html.erb</p>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>